### ISSUE TITLE
Authentifizierung schlägt fehl

### ISSUE THREAD

**Issue by Paddy369** [SmartCity-2022/Service-Bank#11]
Wenn der User angemeldet ist, bekommt man den Error 401 sobald man auf die "Meine Konten" Seite navigiert.

**Comment by dgorpinic** [comment]
Das liegt daran das ich die Tabellen aus der Datenbank gelöscht habe damit diese beim nächsten PR neu generiert wird.
Sollte bei dem nächsten PR  gelöst sein.
